### ISSUE TITLE
Feature request: be able to search people 

### ISSUE THREAD

**Issue by bitcoinuser** [styppo/hamstr#11]
Hi,

Feature request: be able to search people

**Comment by styppo** [comment]
Basic profile search was added in c18c4ed988668e9af4bc19cdccb3df1dfe9e6d9a. It currently only supports searching by pubkey and NIP05 id. It will also find profiles by username if the profiles are locally known, i.e. if we have fetched the profile sometime in this session. To find more people by username, we will have to integrate some sort of indexing service, which is on the roadmap.
