### ISSUE TITLE
When I open a thread then I click back to go to home window, should remember the position. For now jump to top.

### ISSUE THREAD

**Issue by bitcoinuser** [styppo/hamstr#18]
Hi,

When I open a thread then I click back to go to home window, should remember the position. For now jump to top.

Thanks.

**Comment by styppo** [comment]
Should be fixed in c878c9291175d814bc1a23428f43a72e27762b11. Do you still see this issue in the latest version?

**Comment by bitcoinuser** [comment]
Yes, fixed. Tested now. Thanks
