### ISSUE TITLE
If is just a message that is not replying anyone, the replying name shouldn't be shown

### ISSUE THREAD

**Issue by bitcoinuser** [styppo/hamstr#24]
Hi,

If is just a message that is not replying anyone, the replying name shouldn't be shown

![photo_2023-01-25_18-42-02](https://user-images.githubusercontent.com/1178856/214697795-7f4c111f-1d65-42f7-8d3e-03943e001a1f.jpg)

**Comment by styppo** [comment]
This happens if the note is a reply, but the note it is referring to has not been fetched yet. The username appears once that has happened. We can hide the whole line until the username becomes available.

**Comment by bitcoinuser** [comment]
I understand this. No problem to be keep way works now.
